---
# tasks file for ntp
# This file is part of the Ansible role for NTP.
- name: Ensure requirements in place
  ansible.builtin.package:
    name:
      - ntp
    state: present
  become: true

- name: Ensure ntp is running
  ansible.builtin.systemd:
    name: ntpd
    state: started
    enabled: true
  become: true

- name: Configure ntp.conf
  ansible.builtin.template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf
    owner: root
    group: root
    mode: "0644"
  become: true
  notify: Restart ntpd
