[routers]
192.168.0.114 ansible_ssh_user=ansuser


[debian]
192.168.0.126 ansible_ssh_user=ansuser

[docker]
192.168.0.19 ansible_ssh_user=ansuser

[fedora]
192.168.0.188 ansible_ssh_user=ansuser
192.168.0.163 ansible_ssh_user=ansuser