- name: Include install tasks
  ansible.builtin.include_tasks: install.yml
  vars:
    named_zone_dir: "{{ hostvars[inventory_hostname]['named']['named_zone_dir'] }}"

- name: Include authoritative tasks if hostname is in named_master list
  ansible.builtin.include_tasks: authoritative.yml
  vars:
    named_zone_dir: "{{ hostvars[inventory_hostname]['named']['named_zone_dir'] }}"
    named_conf_dir: "{{ hostvars[inventory_hostname]['named']['named_conf_dir'] }}"
  when: hostvars[inventory_hostname]['named']['named_master']|default(False)

- name: Include recursive tasks if hostname is in named_recursive list
  ansible.builtin.include_tasks: recursive.yml
  vars:
    named_zone_dir: "{{ hostvars[inventory_hostname]['named']['named_zone_dir'] }}"
    named_conf_dir: "{{ hostvars[inventory_hostname]['named']['named_conf_dir'] }}"
  when: hostvars[inventory_hostname]['named']['named_recursive']|default(False)
