---
- name: Apply all roles from inventory host01.yml
  hosts: all
  gather_facts: true
  become: true

  tasks:
    - name: Print the role name
      ansible.builtin.debug:
        msg: "Applying role {{ item }}"
      loop: "{{ hostvars[inventory_hostname]['roles'] | default([]) }}"
      when: item is defined

    - name: Include role dynamically
      ansible.builtin.include_role:
        name: "{{ item }}"
      loop: "{{ hostvars[inventory_hostname]['roles'] | default([]) }}"
      when: item is defined
