---
- name: Fedora OS Upgrade
  hosts: '{{ target|default("localhost") }}'
  become: true

  tasks:
    - name: Get current Fedora release
      ansible.builtin.command:
        cmd: cat /etc/fedora-release
      register: current_release

    - name: Set fact for current Fedora release
      ansible.builtin.set_fact:
        current_fedora_release: "{{ current_release.stdout_lines[0].split()[-2] }}"
      when: current_release.stdout_lines[0] is defined

    - block:

        - name: Upgrade to latest packages first
          ansible.builtin.command:
            cmd: dnf upgrade --refresh -y

        - name: Cleanup package cache
          ansible.builtin.command:
            cmd: dnf clean all

        - name: Download Fedora release
          ansible.builtin.command:
            cmd: dnf system-upgrade download --releasever={{ fedora_release|default(40) }} -y --allowerasing

        - name: System Upgrade reboot
          ansible.builtin.command:
            cmd: dnf system-upgrade reboot

        - name: Wait until target host is pingable
          ansible.builtin.wait_for:
            host: '{{ target }}'
            port: 22
            state: started
            delay: 10
            timeout: 3600

      when:
        - current_fedora_release is defined
        - current_fedora_release|int() < fedora_release|default(40)|int()

