---
- name: Install and configure Kea DHCP
  hosts: routers
  become: true

  tasks:
    - name: Install Kea DHCP packages
      ansible.builtin.package:
        name: kea
        state: present

#    - name: Copy Kea DHCP configuration file
#      copy:
#        src: /path/to/kea.conf
#        dest: /etc/kea/kea.conf
#        owner: root
#        group: root
#        mode: 0644

    - name: Start and enable Kea DHCP service
      ansible.builtin.service:
        name: kea-dhcp4
        state: started
        enabled: true

    - name: Start and enable Kea DDNS service
      ansible.builtin.service:
        name: kea-dhcp-ddns
        state: started
        enabled: true
