---
- name: Install and configure BIND9
  hosts: routers
  become: true

  tasks:
    - name: Ensure requirements in place
      ansible.builtin.package:
        name:
          - bind
        state: present
      become: true

    - name: Configure named
      ansible.builtin.template:
        src: named.conf.j2
        dest: /etc/named.conf
        owner: root
        group: named
        mode: "0640"
      notify: Reload named

    - name: Creates directory
      ansible.builtin.file:
        path: /var/named
        state: directory
        owner: root
        group: named
        mode: "0770"

    - name: Update root hints
      ansible.builtin.get_url:
        url: "ftp://ftp.rs.internic.net/domain/db.cache"
        dest: "/var/named/db.cache"
        owner: named
        group: named
        mode: "0640"
      notify: Reload named

    - name: Enable NTP service
      ansible.builtin.service:
        name: named
        state: started
        enabled: true

  handlers:
    - name: Reload named
      ansible.builtin.command: |
        rndc reload
      changed_when: false
...
