---
- name: Sync time and install NTP
  hosts: routers
  become: true

  tasks:
    - name: Install NTP package
      ansible.builtin.package:
        name: ntp
        state: latest

    - name: Synchronize time
      ansible.builtin.shell:
        cmd: pkill ntpd && ntpdate pool.ntp.org
      ignore_errors: true

    - name: Configure rsyslog
      ansible.builtin.template:
        src: ntp.conf.j2
        dest: /etc/ntp.conf
        mode: "0644"
      notify: Restart ntpd

    - name: Enable NTP service
      ansible.builtin.service:
        name: ntpd
        state: started
        enabled: true

  handlers:
    - name: Restart ntpd
      ansible.builtin.service:
        name: ntpd
        state: restarted
