---
- name: Test Sync time and install NTP
  hosts: routers
  become: true
  tasks:
    - name: Check if NTP package is installed
      ansible.builtin.package_facts:
        manager: auto
      register: package_facts


    - name: Assert NTP package is installed
      ansible.builtin.assert:
        that:
          - "'ntp' in package_facts.ansible_facts.packages"

    - name: Check if NTP service is enabled and started
      ansible.builtin.service_facts:
      register: service_facts

    - name: Print package_facts variable
      ansible.builtin.debug:
        var: service_facts


    - name: Assert NTP service is enabled
      ansible.builtin.assert:
        that:
          - service_facts.ansible_facts.services.['ntpd.service'].status == 'enabled'

    - name: Assert NTP service is started
      ansible.builtin.assert:
        that:
          - service_facts.ansible_facts.services.['ntpd.service'].state == 'started'

...